[project]
name = "subscriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery[redis]",
    "sqlalchemy",
    "asyncpg",
    "uvloop",
    "kombu[amazon]>=5.5.4",
    "boto3>=1.38.31",
]
