services:
  # Main submissions database
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: submissions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Problems database (separate from submissions)
  problems-db:
    image: postgres:13
    environment:
      POSTGRES_DB: problems
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - problems_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"  # Different port to avoid conflict

  # Redis for Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Web application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/submissions
      - PROBLEMS_DATABASE_URL=postgresql://postgres:postgres@problems-db:5432/problems
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - problems-db
      - redis
    volumes:
      - ./app:/app/app

volumes:
  postgres_data:
  problems_postgres_data: