# Dockerfile

FROM python:3.9-slim

WORKDIR /app

# Install Python deps
COPY requirements.txt .
RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copy everything into /app
COPY . .

# Expose port
EXPOSE 5000

# Tell Gunicorn to look for `app.main:app`
CMD ["gunicorn", "--chdir", "app", "--bind", "0.0.0.0:5000", "main:app"]
