FROM python:3.10-slim
WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential libpq-dev && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
RUN pip install --target=/install -r requirements.txt


FROM python:3.10-slim
WORKDIR /app
COPY --from=builder /install /usr/local/lib/python3.10/site-packages
COPY . .
EXPOSE 5000

ENV FLASK_ENV=production
ENV USE_SQS=false

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "main:app", "--workers", "4"]
