version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: submissions
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/submissions
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    # Change directory into app/ and run Gunicorn on main:app
    command: gunicorn --chdir app --bind 0.0.0.0:5000 main:app

  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/submissions
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    # Change directory into app/ so Celery finds queue_utils and worker modules
    command: bash -c "cd app && celery -A queue_utils.celery_app worker --loglevel=info -Q pythonq"

volumes:
  db_data:
