FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir uv
COPY pyproject.toml ./
COPY . problems
ENV PATH="/venv/bin:$PATH"
ENV PYTHONPATH=/app
RUN python -m venv /venv && \
    /venv/bin/pip install --no-cache-dir -e .
COPY launch.sh /app/launchapp.sh
EXPOSE 6400
RUN chmod +x /app/launchapp.sh
ENTRYPOINT [ "/app/launchapp.sh" ]

