services:
  authentication_service:
    build: { 
      context: ../../services/auth, 
      dockerfile:  ../../infrastructure/docker/Dockerfile.authentication 
    }
    container_name: authentication_service
    restart: unless-stopped
    environment:
      USER_DATABASE_URL: "postgres://${USER_DATABASE_USER}:${USER_DATABASE_PASSWORD}@user_database:5432/${USER_DATABASE_NAME}?sslmode=disable"
    env_file:
      - ../../.env
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      - user_database
      - redis

  user_database:
    image: postgres:15
    container_name: user_database
    restart: unless-stopped
    ports:
      - "${USER_DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${USER_DATABASE_USER}
      POSTGRES_PASSWORD: ${USER_DATABASE_PASSWORD}
      POSTGRES_DB: ${USER_DATABASE_NAME}
    volumes:
      - user_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  application:
    build: { 
      context: ../../services/frontend, 
      dockerfile:  ../../infrastructure/docker/Dockerfile.application 
    }
    container_name: application
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - "${FRONTEND_PORT}:8080"
    depends_on:
      - authentication_service

volumes:
  user_data:
  redis_data:
