FROM node:20 AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM node:20-slim
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/index.js .
COPY --from=builder /app/package.json ./
RUN npm install --omit=dev
EXPOSE 8080
CMD ["node", "index.js"]